# Gemfile
source "https://rubygems.org"

gem "sass", "~> 3.4.7"
gem "compass", "~> 1.0.1"
gem 'modular-scale', '~> 2.0.5'
gem "susy", "~> 2.1.3"
gem "ffi", "1.9.3"
gem 'autoprefixer-rails', '~> 4.0.1'
